---
title: Generator
---
classDiagram

RandomClass2 <|-- RandomClass1

class RandomClass2 {
attr1: str
attr2: str

func()
func2()

}

RandomClass3 <|-- RandomClass1

class RandomClass3 {
attr1: str
attr2: str

func()
func2()

}


class RandomClass1 {
attr1: str
attr2: str
attr3: list
attr4: RuntimeError


}

