---
title: Generator
---
classDiagram

RandomClass2 <|-- RandomClass1

class RandomClass2 { 
attr1: str
attr2: str
attr3: str

function()
method1()

}

RandomClass3 <|-- RandomClass2

class RandomClass3 { 
attr1: str
attr2: str

function()

}


class RandomClass1 { 
attr1: str
attr2: str
attr3: list
attr4: RuntimeError


}

